version: '3'
services:
  web:
    build:
      context: . # specify where files and folder we need to pull, current working directory
      dockerfile: Dockerfile.dev # location of the docker file
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app # map current folder to /app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test'] #override the command
